name: Daily Thread

on:
  schedule:
    - cron: '{{schedule.daily}}'
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: birdcar/birdhouse@main
      - run: bh daily
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
