name: Test the birdhouse CLI
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: birdcar/birdhouse@main
      - name: Run birdhouse help command
        shell: bash
        run: brdhs --help
      - name: Run birdhouse build command
        shell: bash
        run: brdhs build
